server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ewm-eureka:8761/eureka

spring:
  application:
    name: ApiGateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: mate-service
          uri: lb://mate-service
          predicates:
            - Path=/mate-service/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
