server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ApiGateway-service
  cloud:
    gateway:
      routes:
        - id: ewm1
          uri: lb://ewm1
          predicates:
            - Path=/ewm1/**
        - id: ewm2
          uri: lb://ewm2
          predicates:
            - Path=/ewm2/**
